### ISSUE TITLE
Install error: compilation failed

### ISSUE THREAD

**Issue by xuexiao77** [KaiyangZ/PRIMUS#1]
Hello! I am trying to install the package but failed. 

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c primus.c -o primus.o
primus.c:8:10: fatal error: Rinterface.h: No such file or directory
 #include "Rinterface.h"
          ^~~~~~~~~~~~~~
compilation terminated.

I would appreciate it if you could help me solve this problem! Thank you.

**Comment by Linpu2023** [comment]
Hi did you solve it? I have the same problem...

I found something related: https://github.com/r-lib/rlang/pull/510
According to the issue, it should work if change <Rinterface.h> into <R_ext/GraphicsEngine.h> in this line 8:
![image](https://github.com/KaiyangZ/PRIMUS/assets/122129621/2bb0b789-c8fb-4e19-a9ee-440f8d5cf985)

I modified the code, and for people with the same problem, try:
devtools::install_github("Linpu2023/PRIMUS")
84c3be502eb2d8a72b2eb43d49e60cf89fc829a0
