### ISSUE TITLE
Script to generate simulated data

### ISSUE THREAD

**Issue by pedrofale** [KaiyangZ/PRIMUS#2]
Thank you for the great package.

Could you please add the script that you used to generate the simulated data you describe in the paper and use in the quickstart vignette?

Thanks,
Pedro

**Comment by KaiyangZ** [comment]
Hi Pedro, 

I added the codes to generate the simulated data in the folder `simulations`. 

Best,
Kaiyang

**Comment by pedrofale** [comment]
Thank you very much, Kaiyang!
